### ISSUE TITLE
NameError: global name 'HostFromGpu' is not defined

### ISSUE THREAD

**Issue by zhangxiangnick** [dnouri/kfkd-tutorial#8]
I got this error:
Traceback (most recent call last):
  File "kfkd.py", line 419, in <module>
    func(*sys.argv[2:])
  File "kfkd.py", line 224, in fit
    net.fit(X, y)
  File "/home/ubuntu/src/nolearn/nolearn/lasagne.py", line 145, in fit
    self.y_tensor_type,
  File "/home/ubuntu/src/nolearn/nolearn/lasagne.py", line 283, in _create_iter_funcs
    output_layer.get_output(X_batch), y_batch)
  File "/home/ubuntu/src/lasagne/lasagne/layers/base.py", line 111, in get_output
    layer_input = self.input_layer.get_output(input, *args, **kwargs)
  File "/home/ubuntu/src/lasagne/lasagne/layers/base.py", line 111, in get_output
    layer_input = self.input_layer.get_output(input, *args, **kwargs)
  File "/home/ubuntu/src/lasagne/lasagne/layers/base.py", line 111, in get_output
    layer_input = self.input_layer.get_output(input, *args, **kwargs)
  File "/home/ubuntu/src/lasagne/lasagne/layers/base.py", line 111, in get_output
    layer_input = self.input_layer.get_output(input, *args, **kwargs)
  File "/home/ubuntu/src/lasagne/lasagne/layers/base.py", line 111, in get_output
    layer_input = self.input_layer.get_output(input, *args, **kwargs)
  File "/home/ubuntu/src/lasagne/lasagne/layers/base.py", line 111, in get_output
    layer_input = self.input_layer.get_output(input, *args, **kwargs)
  File "/home/ubuntu/src/lasagne/lasagne/layers/base.py", line 111, in get_output
    layer_input = self.input_layer.get_output(input, *args, **kwargs)
  File "/home/ubuntu/src/lasagne/lasagne/layers/base.py", line 111, in get_output
    layer_input = self.input_layer.get_output(input, *args, **kwargs)
  File "/home/ubuntu/src/lasagne/lasagne/layers/base.py", line 111, in get_output
    layer_input = self.input_layer.get_output(input, *args, **kwargs)
  File "/home/ubuntu/src/lasagne/lasagne/layers/base.py", line 111, in get_output
    layer_input = self.input_layer.get_output(input, *args, **kwargs)
  File "/home/ubuntu/src/lasagne/lasagne/layers/base.py", line 111, in get_output
    layer_input = self.input_layer.get_output(input, *args, **kwargs)
  File "/home/ubuntu/src/lasagne/lasagne/layers/base.py", line 111, in get_output
    layer_input = self.input_layer.get_output(input, *args, **kwargs)
  File "/home/ubuntu/src/lasagne/lasagne/layers/base.py", line 112, in get_output
    return self.get_output_for(layer_input, *args, **kwargs)
  File "/home/ubuntu/src/lasagne/lasagne/layers/cuda_convnet.py", line 144, in get_output_for
    conved += biases
  File "/home/ubuntu/src/theano/theano/tensor/var.py", line 128, in __add__
    return theano.tensor.basic.add(self, other)
  File "/home/ubuntu/src/theano/theano/gof/op.py", line 488, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/ubuntu/src/theano/theano/tensor/elemwise.py", line 527, in make_node
    inputs = map(as_tensor_variable, inputs)
  File "/home/ubuntu/src/theano/theano/tensor/basic.py", line 145, in as_tensor_variable
    return x._as_TensorVariable()  # TODO: pass name and ndim arguments
  File "/home/ubuntu/src/theano/theano/sandbox/cuda/var.py", line 30, in _as_TensorVariable
    return HostFromGpu()(self)
NameError: global name 'HostFromGpu' is not defined

I also got the error "ERROR (theano.sandbox.cuda): nvcc compiler not found on $PATH. Check your nvcc installation and try again.". I checked nvcc is installed under /usr/local/cuda-6.5/bin and included in the $PATH.

**Comment by zhangxiangnick** [comment]
I try to fix it by setting $CUDA_ROOT=/usr/local/cuda-6.5, then I got a different error
ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: libcublas.so.6.5: cannot open shared object file: No such file or directory
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu0 is not available  (error: cuda unavilable)

**Comment by zhangxiangnick** [comment]
The problem is fixed. 

It turns out when I run theano, I used sudo, which changed the $PATH.

**Comment by zirohut** [comment]
@zhangxiangnick 

Hi, I encountered the same problem. But I still can't fix it. Can you be more specific how it changed the $PATH? 

Thank you.

**Comment by zhangxiangnick** [comment]
Hi @zirohut,

Check your environment variable $PATH and $LD_LIBRARY_PATH. I assume you
also did
"echo -e "\nexport PATH=/usr/local/cuda-6.5/bin:$PATH\n\nexport
LD_LIBRARY_PATH=/usr/local/cuda-6.5/lib64" >> .bashrc" as mentioned in the
setup.py. These would change $PATH and $LD_LIBRARY_PATH in user account,
but not in sudo!

My fix is just
sudo env PATH=$PATH LD_LIBRARY_PATH=$LD_LIBRARY_PATH python
your_program_here.py

This would make sure in the sudo mode the $PATH and $LD_LIBRARY_PATH are
still linked to cuda-6.5 and cuda-6.5/lib64.

Let me know if you have any questions. Good Luck!

Xiang

**Comment by zirohut** [comment]
@zhangxiangnick 

It works. Thanks!!
